/* mm-strings.js — 足跡側(u.html,之後 me.html)的 UI 字典與語言解析。
   語言決定順序:?hl= 參數(en|zh-hant|zh-hans) → Worker 注入的 window.MM_HL → navigator.language → zh-hant。
   語言必須進網址(?hl=)才能被搜尋引擎分語言收錄(Google 官方指引 + Strava/X 實務,
   見 docs/DESIGN_username_sharing.md);navigator 只是給「沒帶參數的真人」的禮貌預設。
   zh-hans:P1 暫用 zh-hant 字典顯示(未接 OpenCC;主站 chrome 已有此機制,之後統一)。 */
(function () {
  var STR = {
    'zh-hant': {
      // ---- u.html 靜態 ----
      nav_theatres: '所有劇院', nav_map: '地圖首頁', nav_guide: '怎麼使用', nav_create: '＋ 建立你自己的',
      nav_mine: '我的音樂劇', tagline_theatres: '全球音樂劇場館地圖', search_ph_theatres: '搜尋劇院、城市…（中／英／原文皆可）',
      nav_privacy: '隱私權政策', nav_terms: '使用條款', nav_about: '關於本站',
      th_midnight: '午夜（暗）', th_gallery: '畫廊白（亮）', th_cream: '節目單奶油（亮）', th_neon: '霓虹（暗）', th_deco: '裝飾金（暗）',
      aria_theme: '主題底色', aria_seg: '檢視模式', aria_sort: '排序', aria_close: '關閉',
      hero_sub: '每看一場，蓋一個章',
      seg_poster: '海報牆', seg_passport: '護照', seg_log: '清單',
      sort_date: '最近觀看', sort_rating: '評分', sort_count: '次數', sort_title: '劇名',
      sec_map: '我的音樂劇足跡', sec_map_hint: '點一座城市，只看那裡的收藏',
      aria_zoom_in: '放大', aria_zoom_out: '縮小', aria_zoom_reset: '重置',
      map_hint: '滾輪縮放 · 拖曳平移',
      legend_dot: '圓點 = 看過音樂劇的城市', legend_size: '圓大小 = 看的場數',
      sec_stats: '觀劇統計',
      st_shows: '最常看的音樂劇', st_countries: '最常去的國家', st_cities: '最常去的城市', st_theatres: '最常去的劇院',
      st_year: '各年', st_month: '各月', st_week: '各星期',
      sec_you: '關於這位劇迷', sec_you_me: '關於你', badges_title: '成就徽章',
      footer_1: '海報牆與護照，是同一批收藏的兩種看法。',
      footer_2: '封面取自各劇官方與公開資料。想擁有自己的音樂劇護照？', footer_credit: '封面取自各劇官方與公開資料。',
      footer_cta: '建立你自己的 →',
      empty_title: '找不到這個公開頁', empty_sub: '這個收藏頁不存在，或擁有者尚未公開。',
      empty_cta: '＋ 建立你自己的 My Musicals',
      dt_zoom: '↗ 點圖開新分頁看原圖',
      // ---- u-view.js runtime ----
      bn_musicals: '音樂劇 Musicals', bn_unique: '不同作品 Unique', bn_cities: '城市 Cities', bn_countries: '國家 Countries',
      newest_label: '最新一場', none_yet: '還沒看過任何一場',
      upcoming_dot_n: '· 即將 {n} 場', upcoming_n: '即將 {n} 場',
      chip_all: '全部', ribbon_upcoming: '即將上演', up_mark: '即將<br>上演', up_suffix: '（即將上演）', detail_suffix: ' 詳情',
      n_musicals: '{n} 部音樂劇',
      lt_show: '劇目', lt_city: '城市', lt_date: '日期', lt_rate: '評分', lt_tbd: '未定',
      date_tbd: '日期未定',
      pin_aria: '{city} · {n} 部音樂劇',
      citylist_title: '造訪城市 Cities', citylist_sub: '{c} 座城市 · {k} 國 · 共 {t} 場',
      badge_shows: '{n} 場演出', badge_countries: '{n} 國蓋章', badge_cities: '{n} 座城市',
      badge_unique: '{n} 部不同作品', badge_fav: '{n} 部最愛',
      persona_title: '你是什麼樣的劇迷？',
      dt_venue: '劇院', dt_city: '城市', dt_date: '日期', dt_time: '時間', dt_seat: '座位', dt_price: '票價', dt_link: '連結', dt_open_link: '開啟連結',
      h1_suffix: '{name} 的音樂劇收藏',
      // ---- data.js personality(me/u 共用) ----
      p_G: '環球旅人', p_L: '在地常客', p_Y: '念舊死忠', p_X: '嚐鮮探索',
      p_M: '當代派', p_C: '經典派', p_S: '大製作控', p_I: '小劇場魂',
      p_n_countries: '{n} 國', p_repeat: '重看率 {n}%',
      p_blurb_globe: '你橫跨 {n} 國追劇', p_blurb_local_country: '你在 {n} 個國家看過戲', p_blurb_local_place: '你在 {n} 個地方看過戲',
      p_blurb_loyal: '願意為愛的戲二刷三刷', p_blurb_fresh: '幾乎每齣都嚐鮮',
      p_axis_era: '{m} 現代 / {c} 經典', p_axis_scale: '{s} 大 / {i} 小',
      p_blurb_modern: '口味偏當代', p_blurb_classic: '鍾情經典',
      p_blurb_spectacle: '也擋不住大製作的聲光', p_blurb_intimate: '更愛小劇場的親密',
      p_sep: '，', p_end: '。',
      p_need: '再記錄 {n} 齣，這裡就會浮現你的劇迷輪廓。',
      // ---- me.html 專屬(登入頁,localStorage 記語言) ----
      gate_loading: '載入中…', gate_login: '使用 Google 登入',
      gate_signin: '<b style="font-size:26px">我的音樂劇</b><br><span style="opacity:.72;font-size:14.5px;font-weight:500">記下你看過的每一齣音樂劇，收成海報牆、護照與足跡地圖——存在你的帳號，跨裝置同步。</span>',
      gate_secure: '用你的 Google 帳戶安全登入。我們只讀取名稱、email 與頭像，不會代你張貼任何內容。',
      gate_or: '或', gate_email_lead: '用 Email 收驗證碼登入：',
      gate_email_ph: '你的 Email', gate_email_send: '傳送驗證碼', gate_email_sending: '傳送中…',
      gate_email_sent: '6 位數驗證碼已寄到 {email}，輸入下方即可登入（垃圾郵件夾也看一下）。',
      gate_email_code_ph: '6 位數驗證碼', gate_email_verify: '驗證並登入', gate_email_verifying: '驗證中…',
      gate_email_resend: '重寄驗證碼', gate_email_invalid: '請輸入有效的 Email。',
      gate_email_send_fail: '寄送失敗：{msg}', gate_email_bad_code: '驗證碼錯誤或已過期，請重試或重寄。',
      gate_syncing: '同步你的收藏中…', gate_no_backend: '後端尚未設定',
      gate_load_fail: '讀取收藏失敗，請檢查網路後重試。', gate_retry: '重試',
      del_desc: '刪除帳號會永久移除你的所有觀劇紀錄、公開頁與網址名稱，無法復原。', del_account: '刪除我的帳號',
      del_confirm_prompt: '此動作無法復原。請輸入你的網址名稱「{handle}」以確認刪除：', del_confirm_plain: '此動作無法復原。輸入「DELETE」以確認刪除帳號：',
      del_confirm_mismatch: '輸入的名稱不符，已取消。', del_deleting: '刪除中…', del_done: '你的帳號與所有資料已刪除。感謝你曾經使用 MusicalMap。', del_fail: '刪除失敗，請稍後再試：',
      gate_preview: '登入後長這樣——你的海報牆、音樂劇護照與觀劇統計，全部自動生成：',
      gate_browse_map: '先逛演出地圖 →', gate_see_guide: '看看怎麼使用 →',
      nav_logout: '登出', me_hero_title: '我的音樂劇收藏',
      demo_banner_b: '這是範例收藏', demo_banner_rest: ' —— 先讓你看看蓋滿章後的樣子。按右邊加入你第一齣看過的劇，整頁就換成你自己的。',
      demo_cta: '＋ 加入第一齣音樂劇', demo_sub: '範例預覽 · 加入後就換成你的',
      edit_this: '編輯這齣', delete_this: '刪除這齣', edit: '編輯', delete: '刪除',
      fav_this: '標為最愛', unfav_this: '取消最愛',
      save_cloud_fail: '⚠ 儲存到雲端失敗，請檢查網路後再按一次「加入」。（先別關閉，以免這筆遺失）',
      delete_cloud_fail: '刪除失敗，雲端未更新，請檢查網路後再試一次。',
      fab_add: '＋ 加入音樂劇', log_title: '加入音樂劇', lt_undated: '未定',
      handle_input_label: '網址名稱（英文、數字、底線或連字號，1–30 字）',
      pub_public: '公開我的收藏頁', pub_public_sub: '關閉時，就算有連結別人也看不到你的收藏。',
      sfg_title: '公開頁要顯示哪些敏感資訊？',
      show_price: '顯示票價', show_seat: '顯示座位', note_never: '筆記永遠不會出現在公開頁。',
      copy: '複製', copied: '已複製！', copy_manual: '已選取，按 Ctrl+C', later: '之後再說', save: '儲存', saving: '儲存中…',
      acct_title: '帳號設定',
      acct_lead: '網址名稱是你的帳號身分。更改後舊網址會自動轉到新網址，已分享出去的連結不會壞；舊名稱會永久保留給你，別人拿不走。',
      acct_handle_label: '網址名稱 username', acct_display_label: '顯示名稱（公開頁的標題）', cancel: '取消',
      onb_title: '歡迎！取一個你的網址名稱',
      onb_lead: '這是你的帳號身分，也是公開分享網址的一部分。之後可在「帳號設定」更改，舊網址會自動轉到新的。', logout: '登出',
      h_input_hint: '輸入英文、數字、底線或連字號（1–30 字）。', h_reserved: '這個名稱是保留字，換一個。',
      h_current: '這是你目前的網址。', h_checking: '檢查中…',
      h_avail: '✓ {h} 可以用！', h_taken: '✗ {h} 已被使用，換一個。', h_will_check: '儲存時會確認是否重複。',
      h_taken_short: '✗ 已被使用，換一個。', h_bad_format: '只能用英文、數字、底線、連字號（1–30 字）。',
      h_save_fail: '儲存失敗：', chips_tip: '可用的建議：', onb_done: '✓ 完成！',
      url_empty: '先取一個網址名稱。', acct_url_empty: '網址名稱不能空白。',
      saved_redirect: '✓ 已儲存。舊網址會自動轉到新網址。', saved_ok: '✓ 已儲存', display_save_fail: '顯示名稱儲存失敗：',
      confirm_delete: '確定要刪除《{name}》這筆紀錄嗎？\n(刪除後仍可從左下角「復原」救回)',
      this_show: '這齣', deleted: '已刪除《{name}》', undo: '復原',
      // ---- hero 帳號列＋settings.html 專屬設定頁（nav 大頭照選單的 label 內建於 js/mm-acct-menu.js,不走此字典）----
      pc_add: '＋ 加入音樂劇',
      pc_public: '公開中', pc_private: '未公開',
      pc_public_hint: '任何有連結的人都看得到你的收藏頁', pc_private_hint: '只有你看得到，別人就算有連結也看不到',
      pc_joined: '加入於 {y}年{m}月', pc_copy_url: '複製網址',
      pf_sec_identity: '帳號身分', pf_sec_share: '公開分享',
      st_email: '登入帳號', st_saved_auto: '✓ 已生效', st_signing_out: '登出中…',
      adv_zone: '進階操作',
      st_save_hint: '「公開分享」的開關會立即生效；「帳號身分」的修改要按儲存。',
      // ---- me-input.html 專屬(輸入表單,iframe) ----
      mi_h1: '記錄一齣音樂劇', mi_open_log: '＋ 記錄一齣音樂劇', mi_sheet_record: '記錄一齣音樂劇',
      mi_sec_records: '我的觀劇紀錄', mi_not_recorded: '尚未記錄', mi_add: '加入', mi_update: '更新',
      mi_footer_1: '搜尋→選製作→自動帶入→年份優先的日期→存檔蓋章。', mi_footer_2: '紀錄存進你的帳號、跨裝置同步；海報為各劇真實封面。',
      mi_loading_lib: '載入音樂劇資料庫中…',
      mi_search_ph: '打中文或英文音樂劇名…例：歌劇魅影 / phantom', mi_search_hint: '搜尋你看過的音樂劇 —— 中文、英文都行，搜不到也能手動新增。',
      mi_no_result: '音樂劇資料庫裡找不到「{v}」', mi_manual_add: '＋ 手動新增（自己打劇名／城市）',
      mi_musical: '音樂劇', mi_manual_input_lbl: '手動輸入（音樂劇資料庫裡沒有的劇）', mi_manual_title: '手動新增',
      mi_back: '← 返回', mi_back_search: '← 返回搜尋', mi_back_prods: '← 返回版本', mi_back_pick_prod: '← 返回（選製作）',
      fld_title_req: '劇名 *', fld_city: '城市', fld_venue: '劇院', fld_venue_opt: '劇院（選填）',
      ph_city: '例：London / 台北', ph_venue: '例：臺中國家歌劇院', ph_title: '劇名',
      fld_date_opt: '哪一年／月／日看的（選填）', opt_year: '年', opt_month: '月', opt_day: '日',
      mi_month_n: '{n} 月', mi_day_n: '{n} 日',
      fld_time: '時間 Time（選填）', fld_rating: '評分 Rating（選填）', fld_seat: '座位 Seat', ph_seat: '例：Stalls A12 / 一樓 H23',
      fld_price: '票價 Price', ph_cur: '幣別 ▾', fld_note: '心得 Note', ph_note: '那一夜的記憶…',
      ds_hint: '填到「日」才能算星期幾、各月統計；只記得年份也沒關係，之後可再填。',
      ds_hint2: '填到「日」才能算星期幾、各月統計；只記得年份也行。',
      mgeo_hint: '打城市或劇院時會自動對上國家；對得上就能標在地圖。',
      geo_rematch: '改城市／劇院會重新對上國家座標；對不上仍會存文字。',
      geo_no_coord: '找不到座標時仍會存城市/劇院文字（地圖上可能不顯示）。',
      geo_matched: '對上 {c}', geo_matched_map: '對上 {c} · 會標在地圖',
      disclose_open: '＋ 加入細節（評分、座位、票價、心得）', disclose_close: '－ 收起細節',
      pick_prod: '你看的是哪一個製作？', prod_versions: '{n} 個版本', prod_tour: '巡演',
      prod_cities: '{n} 個城市 · {list}', prod_stations: '{n} 站',
      pick_none: '以上都不是 — 我看的是別的城市／年份', pick_none_sub: '自己填，劇名和海報幫你留著',
      pick_city_q: '{label} — 哪一個城市？', pick_city_none: '不記得是哪個城市', pick_city_none_sub: '先記下這個巡演，城市之後再填',
      run_playing: '本劇在 {city} 上演 {range}', run_recent: '近期在 {city} 上演',
      venue_city: '劇院 · 城市', edit_can_change: '編輯可改', when_seen: '什麼時候看的？', not_required: '非必填',
      star_n: '{n} 顆星', toast_updated: '✓ 已更新這筆紀錄', toast_stamped: '已蓋章！這是你的第 <b>{n}</b> 齣音樂劇',
      date_undated: '日期未定', mi_log_ct_n: '{n} 齣',
      recent_added: '這次加入的 · {n} 齣', recent_added_sub: '加錯了？點 ✎ 改、✕ 刪',
      recent_empty: '搜尋你看過的音樂劇 —— 中文、英文都行，搜不到也能手動新增。', recent_empty_sub: '加好的會即時長到海報牆與護照。',
      mi_edit_record: '編輯紀錄', mi_added: '已加入',
      added_one: '已加入「{name}」！', added_n: '已加入 <b>{n}</b> 齣！',
      batch_hint: '想記日期、評分嗎？點下面那齣就能填；不填也沒關係，回收藏後點海報卡右上角的 <b>✎</b> 隨時都能填。',
      date_later: '日期之後填', seat_label: '座位 <b>{v}</b>', price_label: '票價 <b>{v}</b>', edit_btn: '✎ 編輯',
      add_more: '＋ 再加入一齣', batch_done: '完成，回我的收藏 →',
      fld_poster: '自訂海報網址 Poster URL（選填）', ph_poster: '貼上圖片網址，覆蓋系統海報；清空即還原', poster_prev: '預覽',
      fld_link: '連結 / 售票網址 Link（選填）', ph_link: '貼上這場的售票或節目連結（選填）',
      mi_intro: '大多數人記錄的是以前看過的劇（五年前那一齣），所以日期不預設今天——選了劇，系統用該製作的演出區間幫你回憶是哪一年；劇院／城市／海報全自動帶入，你幾乎不用打字。',
      mi_hint: '試試：打「歌劇魅影」或「phantom」或「les mis」。資料來自 MusicalMap 的音樂劇資料庫。',
      mi_stamp_here: '蓋章<br>處', mi_empty_passport: '你的音樂劇護照還是空白的。<br><b>按上面「＋ 記錄一齣音樂劇」</b>蓋下第一個印章。',
      // ---- how.html 使用說明頁 ----
      how_title: '怎麼使用 — MusicalMap',
      how_meta: 'MusicalMap 怎麼用：一張地圖看全世界正在上演的音樂劇，把你看過的每一齣記成一本音樂劇護照，分享出去。',
      how_nav_start: '我的音樂劇', how_eyebrow: '怎麼使用',
      how_hero: '一張地圖，<br>看見全世界正在上演的<em>音樂劇</em>。',
      how_lede: '免登入就能探索此刻全球正在上演的音樂劇——百老匯、倫敦西區、各國巡演。登入之後，把你看過的都記成一本音樂劇護照，分享出去。',
      how_cta_map: '探索演出地圖', how_cta_me: '建立我的音樂劇護照',
      how_p1_h: '探索，不必註冊', how_p1_lede: '打開地圖，全球此刻正在上演的音樂劇一次看盡。放大、拖一拖，看看世界哪個角落的燈正亮著。',
      how_a1_n: '在地圖上', how_a1_h: '每張海報，都是一齣正在上演的劇', how_a1_p: '地圖上的標記就是各音樂劇的海報，相鄰的會聚成一顆數字圓圈——數字是那一帶正在演的場數。點一張海報，看檔期、劇院與售票連結。',
      how_a1_p2: '底部的月份時間軸可以拖到未來的月份，看那個月全球在演什麼；按 ▶ 可以自動逐月播放，看巡演在城市之間移動分布變化。',
      how_a2_n: '一鍵訂票', how_a2_h: '看到喜歡的，直接過去訂', how_a2_p: '每一齣都附售票連結，多數還有官方網站。我們不賣票——只把你帶到對的地方。',
      how_bridge: '看過的那些，別讓它們只留在記憶裡。',
      how_p2_h: '記下你看過的每一齣', how_p2_lede: '登入之後，你看過的劇會長成一面海報牆、一本蓋章護照，還有你的觀劇統計。全部自動生成。',
      how_b0_n: '你的海報牆', how_b0_h: '看過的，掛成一面牆', how_b0_p: '每加一齣，海報就掛上牆；點卡片上的 ♥，標下你的最愛。海報牆、護照、清單——同一批收藏，三種看法。',
      how_b1_n: '加入一齣', how_b1_h: '搜音樂劇名，其餘自動帶入', how_b1_p: '中英文搜尋都行，劇院、城市、海報自動補上。填看劇的日期、評分、座位、心得——只記得年份也沒關係。每看一場，護照上就多一個章。',
      how_b15_n: '獨家', how_b15_h: '海報與連結，都能換成你的', how_b15_p: '每一齣都能貼上自訂海報網址——用你記得的那一版劇照，即時預覽。再附一條連結，把當年的節目頁或售票頁存進詳情，隨時點開。',
      how_b2_n: '你的觀劇統計', how_b2_h: '看久了，會浮現一個輪廓', how_b2_p: '最常看的音樂劇、去過的城市與國家、各年各月的觀劇分布——都幫你統計好了，一眼看出你是什麼樣的劇迷。',
      how_b3_n: '分享出去', how_b3_h: '你的個人專屬頁面，一鍵就能分享', how_b3_p: '登入取的名字就是你的專屬網址；到「分享」設定公開，這一頁就能傳給朋友。票價、座位要不要公開由你決定；筆記永遠只有你看得到。',
      how_b4_n: '登入很單純', how_b4_h: '用 Google 登入，跨裝置同步', how_b4_p: '我們只讀你的名稱、email 與頭像（頭像只顯示在你自己登入後的選單，不會出現在公開頁），不會代你張貼任何內容。你的收藏存在帳號裡，換手機、換電腦都在。',
      how_final_h: '從哪裡開始都可以', how_final_p: '先逛地圖找靈感，或直接記下你看過的第一齣。', how_final_cta: '建立我的音樂劇護照', how_final_cta2: '先探索地圖',
      how_footer: 'MusicalMap — 全球音樂劇即時地圖，與你的音樂劇護照。', how_footer_link: '回到地圖',
      how_final_about: '這個網站由一位音樂劇迷獨立打造——背後的故事 →',
      // ---- about.html(關於頁) ----
      about_title: '關於本站 — MusicalMap',
      about_meta: 'MusicalMap 是一個由劇迷個人打造的網站：一張顯示全球上演中音樂劇的即時地圖，加上一本屬於你自己的音樂劇護照。',
      about_h1: '關於 MusicalMap',
      about_lede: 'MusicalMap 是一個由劇迷個人打造的網站：一張顯示全球上演中音樂劇的即時地圖，加上一本屬於你自己的音樂劇護照。',
      about_s1_h: '為什麼做這個網站',
      about_s1_p1: '我喜歡地圖和地理，也是音樂劇迷——喜歡跑 Stage Door，在台灣、美國、英國都留下看戲的足跡，從百老匯、倫敦西區到各地巡演。',
      about_s1_p2: '想把歷年看過的音樂劇好好收藏起來時，卻發現沒有一個合適的平台，於是決定自己做一個，為自己永久留下這些寶貴的紀錄。',
      about_s1_p3: '因為喜歡地圖，就把世界各地上演中的音樂劇直接放上地圖。做著做著才發現：原來全世界同時有這麼多不同語言的音樂劇在上演。這是一個值得被更多人看見的世界——希望這個網站能幫上一點忙，讓音樂劇被更多人認識。',
      about_s2_h: '這裡有什麼',
      about_s2_li1: '演出地圖：全球 40+ 國上演中與即將上演的音樂劇，每日自動更新；點海報看檔期、劇院與售票連結。',
      about_s2_li2: '我的音樂劇：登入後記錄看過的每一齣——海報牆、蓋章護照、觀劇統計，和一頁能分享給朋友的公開收藏。',
      about_s3_h: '資料哪裡來',
      about_s3_p: '資料每日自動彙整自各官方售票平台與劇院官方來源（Broadway、West End、Ticketmaster、劇団四季／東宝、Interpark、OPENTIX 等）。免責與分潤揭露詳見使用條款。',
      about_s4_h: '聯絡',
      about_s4_p: '錯誤回報、合作，或任何想說的話：contact@themusicalmap.com。',
      // ---- privacy.html / terms.html(法務頁;繁中為底,zh-hans 由 OpenCC 轉,en 用下方字典) ----
      legal_tagline: '此刻全球正在上演的音樂劇', legal_contact: '聯絡',
      pp_title: '隱私權政策 — MusicalMap', pp_h1: '隱私權政策', pp_updated: '最後更新：2026-07-07',
      pp_intro: 'MusicalMap（「本網站」，<a href="https://themusicalmap.com/">themusicalmap.com</a>）是一個由個人經營、呈現全球音樂劇演出的互動地圖。本政策說明我們蒐集什麼資料、如何使用與保存。聯絡方式：<a href="mailto:contact@themusicalmap.com">contact@themusicalmap.com</a>。',
      pp_s1_h: '1. 瀏覽地圖（不需登入）',
      pp_s1_p: '單純瀏覽地圖<strong>不需要帳號</strong>。本網站是託管於 Cloudflare Pages 的靜態網站，<strong>不</strong>放置廣告追蹤碼。我們使用 Cloudflare Web Analytics（無 cookie）與 <strong>Google Analytics</strong> 做流量統計，以瞭解網站使用狀況；Cloudflare 作為主機可能依其政策記錄標準伺服器日誌（如 IP）。',
      pp_s2_h: '2. 「我的音樂劇」（選擇性登入）',
      pp_s2_p: '若你使用「我的音樂劇（My Musicals）」功能，需以 <strong>Google 帳號</strong>登入。此時我們會蒐集與保存：',
      pp_s2_li1: '你的 Google 帳號基本資料——<strong>電子郵件、顯示名稱與頭像</strong>（透過 Google OAuth 取得，用於辨識你的帳號）。<strong>頭像只顯示給你本人</strong>（登入後的導覽選單與帳號設定頁），不會出現在你的公開頁或任何別人看得到的地方；',
      pp_s2_li2: '你<strong>自行新增的觀劇紀錄</strong>（劇名、劇院、日期、評分/筆記等你輸入的內容）。',
      pp_s2_p2: '這些資料儲存於 <strong>Supabase</strong>（Postgres 資料庫），並以列級安全（Row-Level Security）保護，<strong>僅你本人能存取自己的紀錄</strong>。我們不會販售或交換你的個人資料。',
      pp_s2_p3: '我們可能不定期以 email 通知你<strong>重大功能更新</strong>或影響你帳號的服務異動；每封通知都會附上取消訂閱的方式，你也可以來信要求停止。除此之外，我們不會用你的 email 寄送第三方廣告，也不會將它提供給任何人。',
      pp_s3_h: '3. Cookie 與本機儲存',
      pp_s3_p: '登入後，Supabase 會以 cookie / 瀏覽器本機儲存保存你的登入工作階段（session）。<strong>Google Analytics</strong> 會設置統計用 cookie 以區分訪客（匿名流量統計，非廣告用途）。本網站本身<strong>不</strong>放置廣告 cookie。',
      pp_s4_h: '4. 售票連結與分潤（Affiliate）',
      pp_s4_p: '地圖上的售票連結會導向第三方售票平台（如 Ticketmaster、ATG 等）。其中部分<strong>可能為分潤連結</strong>——當你點擊或購票時，本網站可能透過聯盟網路（如 Impact、Partnerize、Awin）獲得少額佣金，<strong>你不會因此多付任何費用</strong>。點擊後，該售票平台或聯盟網路可能依其自身政策於你的瀏覽器設置 cookie；其資料處理受<strong>各該平台的隱私政策</strong>規範，非本網站所能控制。',
      pp_s5_h: '5. 第三方',
      pp_s5_p: '你由本網站連出的售票網站、官方劇院網站等，皆有各自的隱私權與服務條款。本網站不對第三方網站的內容或資料處理負責。',
      pp_s6_h: '6. 你的權利',
      pp_s6_p: '你可隨時於「我的音樂劇」中<strong>編輯或刪除</strong>你的紀錄，或於 Google 帳號設定中撤銷對本網站的授權。若希望我們刪除你的帳號與所有相關資料，請來信 <a href="mailto:contact@themusicalmap.com">contact@themusicalmap.com</a>。',
      pp_s7_h: '7. 兒童',
      pp_s7_p: '本網站非以未成年人為對象，亦不刻意蒐集兒童個人資料。',
      pp_s8_h: '8. 變更',
      pp_s8_p: '本政策可能不定期更新，異動將反映於本頁頂端的「最後更新」日期。',
      tou_title: '使用條款 — MusicalMap', tou_h1: '使用條款', tou_updated: '最後更新：2026-07-03',
      tou_intro: '歡迎使用 MusicalMap（「本網站」）。使用本網站即表示你同意以下條款。聯絡方式：<a href="mailto:contact@themusicalmap.com">contact@themusicalmap.com</a>。',
      tou_s1_h: '1. 服務說明',
      tou_s1_p: '本網站是一個免費的資訊性服務，彙整公開來源呈現全球音樂劇的演出地點與檔期。資料來自各售票平台與官方來源，可能有<strong>延遲、變動或錯誤</strong>。',
      tou_s2_h: '2. 資料準確性與免責',
      tou_s2_p: '本網站<strong>不保證</strong>演出時間、地點、票務狀態或價格之正確性與即時性。<strong>購票或安排行程前，請務必向官方售票管道或劇院再次確認。</strong>本網站對因依賴本站資訊所生之任何損失，於法律允許範圍內不負責任。服務以「現狀」提供，不附任何明示或默示擔保。',
      tou_s3_h: '3. 售票連結與分潤揭露',
      tou_s3_p: '地圖上的售票連結導向第三方平台；部分<strong>可能為分潤連結</strong>，本網站可能因此獲得少額佣金，<strong>你不會多付費用</strong>。實際交易（付款、出票、退換）由各該售票平台依其條款處理，與本網站無涉。',
      tou_s4_h: '4. 第三方連結',
      tou_s4_p: '本網站包含連往第三方網站的連結，僅為方便提供。本網站不對其內容、商品、服務或交易負責，連結不代表背書。',
      tou_s5_h: '5. 帳號與你的內容',
      tou_s5_p: '使用「我的音樂劇」需以 Google 帳號登入。你應對自己輸入的觀劇紀錄負責。你保留你內容的權利；為提供此功能，你授權本網站儲存並向你本人顯示這些內容。你可隨時刪除。我們得移除違法或濫用之內容。',
      tou_s6_h: '6. 可接受使用',
      tou_s6_p: '請勿對本網站進行自動化大量擷取、攻擊、干擾服務，或以任何違法、侵權方式使用本網站。',
      tou_s7_h: '7. 智慧財產',
      tou_s7_p: '演出資料來自公開來源；海報、商標、作品名稱等權利屬各該權利人所有，於本網站僅作識別與資訊用途。本網站之程式碼與原創呈現受著作權保護。',
      tou_s8_h: '8. 準據法',
      tou_s8_p: '本條款依<strong>中華民國（台灣）</strong>法律解釋與適用。',
      tou_s9_h: '9. 變更',
      tou_s9_p: '本條款可能不定期更新，異動將反映於本頁頂端的「最後更新」日期；繼續使用即視為接受。',
    },
    'en': {
      nav_theatres: 'All Theatres', nav_map: 'Map home', nav_guide: 'Guide', nav_create: '＋ Create your own',
      nav_mine: 'My Musicals', tagline_theatres: 'World map of musical-theatre venues', search_ph_theatres: 'Search theatres, cities… (EN / 中文 / native)',
      nav_privacy: 'Privacy', nav_terms: 'Terms', nav_about: 'About',
      th_midnight: 'Midnight (dark)', th_gallery: 'Gallery white (light)', th_cream: 'Playbill cream (light)', th_neon: 'Neon (dark)', th_deco: 'Deco gold (dark)',
      aria_theme: 'Theme', aria_seg: 'View mode', aria_sort: 'Sort', aria_close: 'Close',
      hero_sub: 'One stamp for every show you see',
      seg_poster: 'Posters', seg_passport: 'Passport', seg_log: 'List',
      sort_date: 'Recently seen', sort_rating: 'Rating', sort_count: 'Times seen', sort_title: 'Title',
      sec_map: 'Where I’ve been', sec_map_hint: 'Click a city to see only those shows',
      aria_zoom_in: 'Zoom in', aria_zoom_out: 'Zoom out', aria_zoom_reset: 'Reset',
      map_hint: 'Scroll to zoom · drag to pan',
      legend_dot: 'Dot = a city with shows logged', legend_size: 'Size = number of shows',
      sec_stats: 'Stats',
      st_shows: 'Most-seen musicals', st_countries: 'Top countries', st_cities: 'Top cities', st_theatres: 'Top theatres',
      st_year: 'By year', st_month: 'By month', st_week: 'By weekday',
      sec_you: 'About this theatregoer', sec_you_me: 'About you', badges_title: 'Badges',
      footer_1: 'The poster wall and the passport are two views of the same collection.',
      footer_2: 'Artwork comes from each show’s official and public sources. Want your own musical passport?', footer_credit: 'Poster art from each show’s official and public sources.',
      footer_cta: 'Create your own →',
      empty_title: 'This page doesn’t exist', empty_sub: 'It may have been removed, or the owner hasn’t made it public.',
      empty_cta: '＋ Create your own My Musicals',
      dt_zoom: '↗ Open full-size image in a new tab',
      bn_musicals: 'Musicals', bn_unique: 'Unique shows', bn_cities: 'Cities', bn_countries: 'Countries',
      newest_label: 'Latest', none_yet: 'No shows seen yet',
      upcoming_dot_n: '· {n} upcoming', upcoming_n: '{n} upcoming',
      chip_all: 'All', ribbon_upcoming: 'Coming up', up_mark: 'Coming<br>up', up_suffix: ' (upcoming)', detail_suffix: ' details',
      n_musicals: '{n} musicals',
      lt_show: 'Show', lt_city: 'City', lt_date: 'Date', lt_rate: 'Rating', lt_tbd: 'TBD',
      date_tbd: 'Date TBD',
      pin_aria: '{city} · {n} musicals',
      citylist_title: 'Cities visited', citylist_sub: '{c} cities · {k} countries · {t} shows',
      badge_shows: '{n} shows', badge_countries: '{n} countries stamped', badge_cities: '{n} cities',
      badge_unique: '{n} unique shows', badge_fav: '{n} favourites',
      persona_title: 'What kind of theatregoer are you?',
      dt_venue: 'Theatre', dt_city: 'City', dt_date: 'Date', dt_time: 'Time', dt_seat: 'Seat', dt_price: 'Price', dt_link: 'Link', dt_open_link: 'Open link',
      h1_suffix: '{name}’s Musicals',
      p_G: 'Globetrotter', p_L: 'Hometown regular', p_Y: 'Loyal rewatcher', p_X: 'Explorer',
      p_M: 'Modernist', p_C: 'Classicist', p_S: 'Spectacle lover', p_I: 'Small-stage soul',
      p_n_countries: '{n} countries', p_repeat: '{n}% rewatch rate',
      p_blurb_globe: 'You’ve chased shows across {n} countries', p_blurb_local_country: 'You’ve seen shows in {n} countries', p_blurb_local_place: 'You’ve kept your theatre-going close to home',
      p_blurb_loyal: 'happy to see a beloved show two or three times', p_blurb_fresh: 'almost always trying something new',
      p_axis_era: '{m} modern / {c} classic', p_axis_scale: '{s} big / {i} small',
      p_blurb_modern: 'with tastes that lean contemporary', p_blurb_classic: 'devoted to the classics',
      p_blurb_spectacle: 'unable to resist a big spectacle', p_blurb_intimate: 'partial to the intimacy of a small stage',
      p_sep: ', ', p_end: '.',
      p_need: 'Log a few more shows and your theatre-fan profile will take shape here.',
      gate_loading: 'Loading…', gate_login: 'Sign in with Google',
      gate_signin: '<b style="font-size:26px">My Musicals</b><br><span style="opacity:.72;font-size:14.5px;font-weight:500">Log the musicals you’ve seen and turn them into your poster wall, passport and map — saved to your account, synced across devices.</span>',
      gate_secure: 'Secure sign-in with your Google account. We only read your name, email and avatar — we never post anything on your behalf.',
      gate_or: 'or', gate_email_lead: 'Sign in with an email code:',
      gate_email_ph: 'Your email', gate_email_send: 'Send code', gate_email_sending: 'Sending…',
      gate_email_sent: 'A 6-digit code was sent to {email} — enter it below to sign in (check spam too).',
      gate_email_code_ph: '6-digit code', gate_email_verify: 'Verify & sign in', gate_email_verifying: 'Verifying…',
      gate_email_resend: 'Resend code', gate_email_invalid: 'Please enter a valid email.',
      gate_email_send_fail: 'Failed to send: {msg}', gate_email_bad_code: 'Wrong or expired code — try again or resend.',
      gate_syncing: 'Syncing your collection…', gate_no_backend: 'Backend not configured',
      gate_load_fail: 'Couldn’t load your collection. Check your connection and try again.', gate_retry: 'Retry',
      del_desc: 'Deleting your account permanently removes all your logged shows, your public page and your username. This cannot be undone.', del_account: 'Delete my account',
      del_confirm_prompt: 'This cannot be undone. Type your username “{handle}” to confirm deletion:', del_confirm_plain: 'This cannot be undone. Type “DELETE” to confirm deleting your account:',
      del_confirm_mismatch: 'That didn’t match — cancelled.', del_deleting: 'Deleting…', del_done: 'Your account and all data have been deleted. Thank you for using MusicalMap.', del_fail: 'Deletion failed, please try again later:',
      gate_preview: 'After you sign in — your poster wall, theatre passport and stats, all generated automatically:',
      gate_browse_map: 'Browse the map first →', gate_see_guide: 'Read the guide →',
      nav_logout: 'Sign out', me_hero_title: 'My Musicals',
      demo_banner_b: 'This is a sample collection', demo_banner_rest: ' — a preview of what it looks like once stamped. Add your first show on the right and the whole page becomes yours.',
      demo_cta: '＋ Add your first musical', demo_sub: 'Sample preview · becomes yours once you add a show',
      edit_this: 'Edit this show', delete_this: 'Delete this show', edit: 'Edit', delete: 'Delete',
      fav_this: 'Mark as favourite', unfav_this: 'Remove favourite',
      save_cloud_fail: '⚠ Couldn’t save to the cloud. Check your connection and tap “Add” again. (Don’t close yet, or this entry may be lost.)',
      delete_cloud_fail: 'Delete failed — the cloud wasn’t updated. Check your connection and try again.',
      fab_add: '＋ Add a musical', log_title: 'Add a musical', lt_undated: 'TBD',
      handle_input_label: 'URL name (letters, digits, underscore or hyphen, 1–30 chars)',
      pub_public: 'Make my collection public', pub_public_sub: 'When off, no one can see your collection even with the link.',
      sfg_title: 'Which details should appear on your public page?',
      show_price: 'Show price', show_seat: 'Show seat', note_never: 'Notes never appear on the public page.',
      copy: 'Copy', copied: 'Copied!', copy_manual: 'Selected — press Ctrl+C', later: 'Later', save: 'Save', saving: 'Saving…',
      acct_title: 'Account settings',
      acct_lead: 'Your URL name is your account identity. After you change it, the old URL redirects to the new one — links you’ve already shared won’t break; the old name stays reserved for you and no one else can take it.',
      acct_handle_label: 'URL name (username)', acct_display_label: 'Display name (the public page title)', cancel: 'Cancel',
      onb_title: 'Welcome! Pick your URL name',
      onb_lead: 'This is your account identity and part of your public share URL. You can change it later in Account settings — the old URL will redirect to the new one.', logout: 'Sign out',
      h_input_hint: 'Letters, digits, underscore or hyphen (1–30 chars).', h_reserved: 'That name is reserved. Try another.',
      h_current: 'This is your current URL.', h_checking: 'Checking…',
      h_avail: '✓ {h} is available!', h_taken: '✗ {h} is taken. Try another.', h_will_check: 'We’ll check availability when you save.',
      h_taken_short: '✗ Taken. Try another.', h_bad_format: 'Only letters, digits, underscore, hyphen (1–30 chars).',
      h_save_fail: 'Save failed: ', chips_tip: 'Available suggestions:', onb_done: '✓ Done!',
      url_empty: 'Pick a URL name first.', acct_url_empty: 'URL name can’t be empty.',
      saved_redirect: '✓ Saved. The old URL will redirect to the new one.', saved_ok: '✓ Saved', display_save_fail: 'Display name save failed: ',
      confirm_delete: 'Delete “{name}” from your records?\n(You can still restore it from “Undo” at the bottom-left.)',
      this_show: 'this show', deleted: 'Deleted “{name}”', undo: 'Undo',
      pc_add: '＋ Add a musical',
      pc_public: 'Public', pc_private: 'Private',
      pc_public_hint: 'Anyone with the link can see your collection', pc_private_hint: 'Only you can see it — the link won’t work for anyone else',
      pc_joined: 'Joined {m} {y}', pc_copy_url: 'Copy link',
      pf_sec_identity: 'Account identity', pf_sec_share: 'Public sharing',
      st_email: 'Signed in as', st_saved_auto: '✓ Applied', st_signing_out: 'Signing out…',
      adv_zone: 'Advanced',
      st_save_hint: 'Public-sharing toggles apply instantly; account-identity changes need Save.',
      mi_h1: 'Log a musical', mi_open_log: '＋ Log a musical', mi_sheet_record: 'Log a musical',
      mi_sec_records: 'My records', mi_not_recorded: 'Nothing logged yet', mi_add: 'Add', mi_update: 'Update',
      mi_footer_1: 'Search → pick production → auto-fill → year-first date → save & stamp.', mi_footer_2: 'Records are saved to your account and synced across devices; artwork is each show’s real cover.',
      mi_loading_lib: 'Loading catalogue…',
      mi_search_ph: 'Type a title in English or Chinese… e.g. phantom / les mis', mi_search_hint: 'Search musicals you’ve seen — English or Chinese; not found? add it manually.',
      mi_no_result: 'No results for “{v}” in the catalogue', mi_manual_add: '＋ Add manually (type your own title / city)',
      mi_musical: 'Musical', mi_manual_input_lbl: 'Manual entry (for shows not in the catalogue)', mi_manual_title: 'Add manually',
      mi_back: '← Back', mi_back_search: '← Back to search', mi_back_prods: '← Back to versions', mi_back_pick_prod: '← Back (pick production)',
      fld_title_req: 'Title *', fld_city: 'City', fld_venue: 'Theatre', fld_venue_opt: 'Theatre (optional)',
      ph_city: 'e.g. London / Taipei', ph_venue: 'e.g. National Taichung Theater', ph_title: 'Title',
      fld_date_opt: 'When did you see it? Year / month / day (optional)', opt_year: 'Year', opt_month: 'Month', opt_day: 'Day',
      mi_month_n: '{n}', mi_day_n: '{n}',
      fld_time: 'Time (optional)', fld_rating: 'Rating (optional)', fld_seat: 'Seat', ph_seat: 'e.g. Stalls A12 / Circle H23',
      fld_price: 'Price', ph_cur: 'Currency ▾', fld_note: 'Note', ph_note: 'Memories of that night…',
      ds_hint: 'Add the exact date for weekday & monthly stats; just the year is fine — you can fill in the rest later.',
      ds_hint2: 'Add the exact date for weekday & monthly stats; just the year works too.',
      mgeo_hint: 'Typing a city or theatre auto-matches the country; if matched, it’s pinned on the map.',
      geo_rematch: 'Changing city/theatre re-matches country coordinates; unmatched still saves as text.',
      geo_no_coord: 'If no coordinates are found, the city/theatre still saves as text (may not show on the map).',
      geo_matched: 'Matched {c}', geo_matched_map: 'Matched {c} · will pin on map',
      disclose_open: '＋ Add details (rating, seat, price, note)', disclose_close: '－ Hide details',
      pick_prod: 'Which production did you see?', prod_versions: '{n} versions', prod_tour: 'Tour',
      prod_cities: '{n} cities · {list}', prod_stations: '{n} stops',
      pick_none: 'None of these — I saw it in another city/year', pick_none_sub: 'Fill it in yourself; we’ll keep the title and artwork',
      pick_city_q: '{label} — which city?', pick_city_none: 'Don’t remember the city', pick_city_none_sub: 'Log this tour for now, add the city later',
      run_playing: 'Playing in {city} {range}', run_recent: 'Recently in {city}',
      venue_city: 'Theatre · City', edit_can_change: 'editable', when_seen: 'When did you see it?', not_required: 'optional',
      star_n: '{n} stars', toast_updated: '✓ Record updated', toast_stamped: 'Stamped! Musical #<b>{n}</b> in your collection',
      date_undated: 'Date TBD', mi_log_ct_n: '{n}',
      recent_added: 'Added this time · {n}', recent_added_sub: 'Made a mistake? Tap ✎ to edit, ✕ to delete',
      recent_empty: 'Search musicals you’ve seen — English or Chinese; not found? add it manually.', recent_empty_sub: 'What you add grows onto your poster wall and passport instantly.',
      mi_edit_record: 'Edit record', mi_added: 'Added',
      added_one: 'Added “{name}”!', added_n: 'Added <b>{n}</b>!',
      batch_hint: 'Want to log the date or rating? Tap a show below to fill it in — optional; you can always tap ✎ on the poster card later.',
      date_later: 'Add date later', seat_label: 'Seat <b>{v}</b>', price_label: 'Price <b>{v}</b>', edit_btn: '✎ Edit',
      add_more: '＋ Add another', batch_done: 'Done, back to my collection →',
      fld_poster: 'Poster URL (optional)', ph_poster: 'Paste an image URL to override the default; clear to restore', poster_prev: 'Preview',
      fld_link: 'Link / ticket URL (optional)', ph_link: 'Paste the ticket or programme link (optional)',
      mi_intro: 'Most people add shows they saw years ago, so the date isn’t preset to today — pick a show and we use its run dates to help you recall the year; theatre, city and artwork auto-fill, so you barely type.',
      mi_hint: 'Try: type “phantom”, “les mis”, or a Chinese title. Data comes from MusicalMap’s real catalogue.',
      mi_stamp_here: 'stamp<br>here', mi_empty_passport: 'Your passport is still blank — a blank page, so many possibilities.<br><b>Tap “＋ Log a musical” above</b> to add your first stamp.',
      how_title: 'How it works — MusicalMap',
      how_meta: 'How MusicalMap works: one live map of musicals playing worldwide, and a theatre passport for every show you’ve seen.',
      how_nav_start: 'My Musicals', how_eyebrow: 'How it works',
      how_hero: 'One map for<br>every musical playing <em>right now</em>.',
      how_lede: 'Explore what’s on around the world without signing in — Broadway, the West End, tours everywhere. Sign in, and every show you’ve seen becomes a theatre passport you can share.',
      how_cta_map: 'Explore the map', how_cta_me: 'Build your passport',
      how_p1_h: 'Explore — no sign-up', how_p1_lede: 'Open the map and see what’s playing around the world right now — zoom in and find which corners of the world have their lights on.',
      how_a1_n: 'On the map', how_a1_h: 'Every poster on the map is a show playing now', how_a1_p: 'Markers are the musicals’ own posters; neighbouring ones gather into a numbered circle — that’s how many are playing around there. Tap a poster for its dates, theatre and ticket links.',
      how_a1_p2: 'Drag the month timeline at the bottom to any upcoming month to see what’s playing then; press ▶ to play month by month and watch tours move between cities.',
      how_a2_n: 'One tap to tickets', how_a2_h: 'Be in the room where it happens', how_a2_p: 'Every show comes with a ticket link, and most have their official site too. We don’t sell tickets — we just point you to the right place.',
      how_bridge: 'Don’t leave memories all alone in the moonlight — stamp them in.',
      how_p2_h: 'Keep every show you’ve seen', how_p2_lede: 'Once you sign in, your shows grow into a poster wall, a stamped passport and your own viewing stats. All automatic.',
      how_b0_n: 'Your poster wall', how_b0_h: 'What you’ve seen, hung on a wall', how_b0_p: 'Every musical you add hangs its poster on the wall; tap the ♥ on a card to mark a favourite. Poster wall, passport, list — three views of the same collection.',
      how_b1_n: 'Add a musical', how_b1_h: 'Search the title, the rest fills itself in', how_b1_p: 'Search in English or Chinese; theatre, city and poster fill in automatically. Add the date, rating, seat and notes — just the year is fine. Every show you log adds a stamp to your passport.',
      how_b15_n: 'Make it yours', how_b15_h: 'Your own poster, your own link', how_b15_p: 'Give any show a custom poster URL — the artwork you remember it by, previewed instantly. Attach a link too, so that year’s programme or ticket page is always one tap away in its details.',
      how_b2_n: 'Your theatregoing stats', how_b2_h: 'How do you measure a year? In shows, cities and stamps', how_b2_p: 'Most-seen musicals, cities and countries visited, how your theatregoing spreads across years and months — all tallied for you, showing at a glance what kind of theatregoer you are.',
      how_b3_n: 'Share it', how_b3_h: 'Your own personal page, shared in one click', how_b3_p: 'The name you pick at sign-up is your personal URL; flip the switch in “Share” and the page is ready to send to friends. You decide whether price and seat are shown; your notes stay yours alone.',
      how_b4_n: 'Signing in is simple', how_b4_h: 'Sign in with Google, synced everywhere', how_b4_p: 'We only read your name, email and avatar (the avatar appears only in your own signed-in menu, never on public pages) — we never post anything on your behalf. Your collection lives in your account, on every phone and laptop.',
      how_final_h: 'Start anywhere', how_final_p: 'Let’s start at the very beginning — browse the map, or log the first show you ever saw.', how_final_cta: 'Build your passport', how_final_cta2: 'Explore the map first',
      how_footer: 'MusicalMap — a live world map of musicals, and your theatre passport.', how_footer_link: 'Back to the map',
      how_final_about: 'Built by one theatre fan who loves maps — the story →',
      // ---- about.html ----
      about_title: 'About — MusicalMap',
      about_meta: 'MusicalMap is built by one theatre fan: a live world map of musicals playing right now, plus a theatre passport of your own.',
      about_h1: 'About MusicalMap',
      about_lede: 'MusicalMap is built by one theatre fan: a live world map of musicals playing right now, plus a theatre passport of your own.',
      about_s1_h: 'Why this site exists',
      about_s1_p1: 'I love maps and geography, and I’m a musical-theatre fan — the kind who waits at the stage door. I’ve seen shows in Taiwan, the US and the UK: Broadway, the West End, and tours everywhere in between.',
      about_s1_p2: 'When I wanted to gather all the musicals I’d seen over the years, I couldn’t find a platform that did it well — so I decided to build one, to keep those records for good.',
      about_s1_p3: 'And because I love maps, I put every musical playing around the world straight onto one. Building it taught me something: there are far more musicals playing at once, in far more languages, than I ever imagined. That world deserves a bigger audience — I hope this site helps more people find it.',
      about_s2_h: 'What’s here',
      about_s2_li1: 'The live map: musicals playing now and soon across 40+ countries, refreshed daily; tap a poster for dates, theatre and ticket links.',
      about_s2_li2: 'My Musicals: sign in to log every show you’ve seen — a poster wall, a stamped passport, your theatregoing stats, and a public page to share with friends.',
      about_s3_h: 'Where the data comes from',
      about_s3_p: 'Listings are aggregated daily from official ticketing platforms and theatre sources (Broadway, West End, Ticketmaster, Shiki/Toho, Interpark, OPENTIX and more). See the Terms for disclaimers and affiliate disclosure.',
      about_s4_h: 'Contact',
      about_s4_p: 'Corrections, ideas, or anything else: contact@themusicalmap.com.',
      // ---- privacy.html / terms.html ----
      legal_tagline: 'Musicals playing around the world right now', legal_contact: 'Contact',
      pp_title: 'Privacy Policy — MusicalMap', pp_h1: 'Privacy Policy', pp_updated: 'Last updated: 2026-07-07',
      pp_intro: 'MusicalMap ("this site", <a href="https://themusicalmap.com/">themusicalmap.com</a>) is a personally-operated interactive map of musicals playing worldwide. This policy explains what data we collect, and how it is used and stored. Contact: <a href="mailto:contact@themusicalmap.com">contact@themusicalmap.com</a>.',
      pp_s1_h: '1. Browsing the map (no sign-in)',
      pp_s1_p: 'Simply browsing the map requires <strong>no account</strong>. This site is a static website hosted on Cloudflare Pages; we place <strong>no</strong> advertising trackers. We use Cloudflare Web Analytics (cookie-free) and <strong>Google Analytics</strong> to measure traffic and understand how the site is used; Cloudflare, as the host, may record standard server logs (such as IP addresses) under its own policies.',
      pp_s2_h: '2. "My Musicals" (optional sign-in)',
      pp_s2_p: 'If you use the <strong>My Musicals</strong> feature, you sign in with a <strong>Google account</strong>. We then collect and store:',
      pp_s2_li1: 'your basic Google profile — <strong>email address, display name and avatar</strong> (obtained via Google OAuth, used to identify your account). <strong>Your avatar is shown only to you</strong> (in your signed-in navigation menu and account settings) — never on your public page or anywhere visible to others;',
      pp_s2_li2: 'the <strong>show records you add yourself</strong> (title, theatre, date, rating/notes — whatever you enter).',
      pp_s2_p2: 'This data is stored in <strong>Supabase</strong> (a Postgres database) and protected with Row-Level Security, so <strong>only you can access your own records</strong>. We never sell or trade your personal data.',
      pp_s2_p3: 'We may occasionally email you about <strong>major new features</strong> or service changes that affect your account; every such email includes a way to unsubscribe, and you can also opt out by writing to us. Beyond that, we never use your email for third-party advertising, and never share it with anyone.',
      pp_s3_h: '3. Cookies and local storage',
      pp_s3_p: 'After you sign in, Supabase keeps your session in cookies / browser local storage. <strong>Google Analytics</strong> sets analytics cookies to distinguish visitors (anonymous traffic measurement, not advertising). This site itself places <strong>no</strong> advertising cookies.',
      pp_s4_h: '4. Ticket links and affiliates',
      pp_s4_p: 'Ticket links on the map lead to third-party ticketing platforms (such as Ticketmaster or ATG). Some <strong>may be affiliate links</strong> — when you click or buy, this site may earn a small commission through affiliate networks (such as Impact, Partnerize or Awin), <strong>at no extra cost to you</strong>. After you click, the ticketing platform or network may set cookies in your browser under its own policies; their data practices are governed by <strong>their own privacy policies</strong> and are outside our control.',
      pp_s5_h: '5. Third parties',
      pp_s5_p: 'Ticketing sites, official theatre sites and other pages you reach from here each have their own privacy policies and terms. This site is not responsible for third-party content or data practices.',
      pp_s6_h: '6. Your rights',
      pp_s6_p: 'You can <strong>edit or delete</strong> your records in My Musicals at any time, or revoke this site’s access in your Google account settings. To have your account and all related data deleted, email <a href="mailto:contact@themusicalmap.com">contact@themusicalmap.com</a>.',
      pp_s7_h: '7. Children',
      pp_s7_p: 'This site is not directed at minors and does not knowingly collect children’s personal data.',
      pp_s8_h: '8. Changes',
      pp_s8_p: 'This policy may be updated from time to time; changes are reflected in the "Last updated" date at the top of this page.',
      tou_title: 'Terms of Use — MusicalMap', tou_h1: 'Terms of Use', tou_updated: 'Last updated: 2026-07-03',
      tou_intro: 'Welcome to MusicalMap ("this site"). By using this site you agree to these terms. Contact: <a href="mailto:contact@themusicalmap.com">contact@themusicalmap.com</a>.',
      tou_s1_h: '1. The service',
      tou_s1_p: 'This site is a free, informational service that aggregates public sources to show where and when musicals are playing worldwide. Data comes from ticketing platforms and official sources and may be <strong>delayed, changed or wrong</strong>.',
      tou_s2_h: '2. Accuracy and disclaimer',
      tou_s2_p: 'This site does <strong>not guarantee</strong> the accuracy or timeliness of showtimes, venues, ticket availability or prices. <strong>Always confirm with the official box office or theatre before buying tickets or making travel plans.</strong> To the extent permitted by law, this site accepts no liability for losses arising from reliance on its information. The service is provided "as is", without warranties of any kind.',
      tou_s3_h: '3. Ticket links and affiliate disclosure',
      tou_s3_p: 'Ticket links lead to third-party platforms; some <strong>may be affiliate links</strong>, from which this site may earn a small commission — <strong>at no extra cost to you</strong>. All transactions (payment, ticketing, refunds) are handled by the respective platform under its own terms and are unrelated to this site.',
      tou_s4_h: '4. Third-party links',
      tou_s4_p: 'Links to third-party websites are provided for convenience only. This site is not responsible for their content, goods, services or transactions, and links do not imply endorsement.',
      tou_s5_h: '5. Your account and content',
      tou_s5_p: 'My Musicals requires signing in with a Google account. You are responsible for the records you enter. You retain the rights to your content; to provide the feature, you grant this site permission to store it and display it back to you. You may delete it at any time. We may remove unlawful or abusive content.',
      tou_s6_h: '6. Acceptable use',
      tou_s6_p: 'Do not scrape this site at scale, attack or disrupt the service, or use it in any unlawful or infringing way.',
      tou_s7_h: '7. Intellectual property',
      tou_s7_p: 'Show data comes from public sources; posters, trademarks and titles belong to their respective owners and appear here for identification and information only. This site’s code and original presentation are protected by copyright.',
      tou_s8_h: '8. Governing law',
      tou_s8_p: 'These terms are governed by the laws of the <strong>Republic of China (Taiwan)</strong>.',
      tou_s9_h: '9. Changes',
      tou_s9_p: 'These terms may be updated from time to time; changes are reflected in the "Last updated" date at the top of this page. Continued use constitutes acceptance.',
    },
  };

  // ---- 語言解析(?hl 進網址是 SEO 需求;navigator 只服務沒帶參數的真人) ----
  var q = null;
  try { q = new URLSearchParams(location.search).get('hl'); } catch (e) {}
  var hl = (q === 'en' || q === 'zh-hant' || q === 'zh-hans') ? q : null;
  if (!hl && window.MM_HL && STR[window.MM_HL === 'zh-hans' ? 'zh-hant' : window.MM_HL]) hl = window.MM_HL; // Worker 注入
  // 登入頁(me.html)設 MM_USE_LANG_PREF → 讀主站共用的 mm_lang 偏好(en/zh)。公開頁 u.html 不設(語言只認 ?hl=,SEO 需求)。
  if (!hl && window.MM_USE_LANG_PREF) {
    try {
      var mv = localStorage.getItem('mm_variant');   // 主站存 en/zh-hans/zh-hant(精確含簡繁),優先
      if (mv === 'en' || mv === 'zh-hans' || mv === 'zh-hant') hl = mv;
      else { var lp = localStorage.getItem('mm_lang'); if (lp === 'en') hl = 'en'; else if (lp === 'zh') hl = 'zh-hant'; }
    } catch (e) {}
  }
  if (!hl) {
    var nl = (navigator.language || '').toLowerCase();
    if (nl.indexOf('zh') === 0) hl = (nl.indexOf('cn') > -1 || nl.indexOf('hans') > -1 || nl.indexOf('sg') > -1) ? 'zh-hans' : 'zh-hant';
    else if (nl) hl = 'en';
    else hl = 'zh-hant';
  }
  // zh-hans:用 OpenCC(tw→cn)把繁中字典 runtime 轉簡體(沿用主站 i18n.js 機制);OpenCC 未載入則降級繁中。
  // OpenCC 只轉「字」不轉「詞」——台灣用語要再過一層詞彙表(只作用於 UI 字典,不動劇名/地名資料)。
  var CN_FIX = [
    [/登入/g, '登录'], [/登出/g, '退出登录'],
    [/连结/g, '链接'],
    [/每一出/g, '每一部'], [/一出正在上演的剧/g, '一部正在上演的剧'],
    [/建立/g, '创建'],
    [/跨装置/g, '跨设备'], [/装置/g, '设备'],
    [/帐号/g, '账号'], [/帐户/g, '账户'],
    [/本机储存/g, '本地存储'], [/储存/g, '存储'],
    [/工作阶段/g, '会话'],
    [/透过/g, '通过'],
    [/币别/g, '币种'],
    [/资料库/g, '数据库'],
    [/智慧财产/g, '知识产权'],
    [/准据法/g, '适用法律'],
    [/即时/g, '实时'], [/隐私权政策/g, '隐私政策'],
    [/示范资料/g, '示例数据'], [/范例/g, '示例'],
    [/身分/g, '身份'],   // 台灣標準「身分」;大陸標準「身份」
  ];
  function cnFix(s) { for (var i = 0; i < CN_FIX.length; i++) s = s.replace(CN_FIX[i][0], CN_FIX[i][1]); return s; }
  // 簡中「手寫覆蓋層」:OpenCC 只能轉字+CN_FIX 轉詞,句式仍是台灣腔;敘事型長文(About 等)
  // 在此提供大陸語感的手寫版,build 完成後覆蓋自動轉換結果。短 UI 標籤仍走自動轉換。
  var HANS_OVERRIDE = {
    about_lede: 'MusicalMap 由一位剧迷独立打造：一张显示全球在演音乐剧的实时地图，加上一本属于你自己的音乐剧护照。',
    about_s1_p1: '我喜欢地图和地理，也是音乐剧迷——爱蹲 Stage Door，在台湾、美国、英国都留下过看剧的足迹，从百老汇、伦敦西区到各地巡演。',
    about_s1_p2: '想把这些年看过的音乐剧好好收藏起来，却发现没有一个合适的平台，干脆自己动手做一个，把这些宝贵的记录永久留存。',
    about_s1_p3: '因为喜欢地图，就把世界各地在演的音乐剧直接放上了地图。做着做着才发现：原来全世界同时有这么多不同语言的音乐剧在上演。这个世界值得被更多人看见——希望这个网站能帮上一点忙，让音乐剧被更多人认识。',
    about_meta: 'MusicalMap 由一位剧迷独立打造：一张显示全球在演音乐剧的实时地图，加上一本属于你自己的音乐剧护照。',
  };
  var _conv = null;
  if (hl === 'zh-hans') {
    try { _conv = window.OpenCC && window.OpenCC.Converter({ from: 'tw', to: 'cn' }); } catch (e) {}
    if (_conv && !STR['zh-hans']) { var o = {}; for (var k in STR['zh-hant']) o[k] = cnFix(_conv(STR['zh-hant'][k])); STR['zh-hans'] = o; }
    if (STR['zh-hans']) { for (var hk in HANS_OVERRIDE) STR['zh-hans'][hk] = HANS_OVERRIDE[hk]; }
  }
  var D = STR[hl] || STR['zh-hant'];
  // MM_S:把「資料層繁中文字」(劇院/城市/國家名,原始資料)在 zh-hans 也轉簡;其他語言 identity。
  // u-view.js / me.html 的 countryZh/cityName/venueZh 用它,讓簡體頁不殘留繁體地名。
  window.MM_S = _conv ? function (t) { try { return _conv(String(t == null ? '' : t)); } catch (e) { return t; } } : function (t) { return t; };

  window.MM_STR = STR;
  window.MM_HL = hl;
  window.MM_T = function (k) {
    if (D[k] != null) return D[k];
    if (STR['zh-hant'][k] != null) return STR['zh-hant'][k];
    return k;
  };

  // ---- 套用到靜態 DOM:data-i18n(textContent)/-title/-aria;<html lang>;語言切換 pills ----
  function apply() {
    document.documentElement.lang = hl === 'en' ? 'en' : (hl === 'zh-hans' ? 'zh-Hans' : 'zh-Hant');
    if (window.MM_USE_LANG_PREF) { try { localStorage.setItem('mm_lang', hl === 'en' ? 'en' : 'zh'); localStorage.setItem('mm_variant', hl); } catch (e) {} } // 記住偏好(mm_variant 含簡繁,與主站共用)
    document.querySelectorAll('[data-i18n]').forEach(function (el) { el.textContent = window.MM_T(el.getAttribute('data-i18n')); });
    document.querySelectorAll('[data-i18n-ph]').forEach(function (el) { el.placeholder = window.MM_T(el.getAttribute('data-i18n-ph')); });  // placeholder(搜尋框等);i18n.js 有此處理,遷來 mm-strings 需補
    document.querySelectorAll('[data-i18n-html]').forEach(function (el) { el.innerHTML = window.MM_T(el.getAttribute('data-i18n-html')); });  // 含 <br>/<b> 的字串(字典值為信任的 UI 文案,非使用者輸入)
    document.querySelectorAll('[data-i18n-title]').forEach(function (el) { el.title = window.MM_T(el.getAttribute('data-i18n-title')); });
    document.querySelectorAll('[data-i18n-aria]').forEach(function (el) { el.setAttribute('aria-label', window.MM_T(el.getAttribute('data-i18n-aria'))); });
    document.querySelectorAll('[data-i18n-content]').forEach(function (el) { el.setAttribute('content', window.MM_T(el.getAttribute('data-i18n-content'))); });  // <meta> description/og
    // 語言切換:改寫 ?hl= 並保留其他參數(如 ?u=)——連結而非按鈕,爬蟲也能發現語言變體。
    // 繁也要「明寫 ?hl=zh-hant」:若刪參數,簡體/英文瀏覽器會被 navigator 重新偵測回原語言,永遠切不回繁
    // (無參數 URL 仍是 zh-hant canonical,由各頁 hreflang/canonical 標記,同 theatres.html ?lang= 模式)。
    document.querySelectorAll('[data-hl-link]').forEach(function (a) {
      var t = a.getAttribute('data-hl-link');
      if (window.MM_STATIC_VARIANT) {
        // 靜態變體頁(gen_pages.mjs 產的 /{lang}/about 等):語言切換=導向 sibling 變體網址
        a.href = '/' + t + '/' + window.MM_STATIC_VARIANT;
      } else {
        var u = new URL(location.href);
        u.searchParams.set('hl', t);
        a.href = u.pathname + (u.search || '');
      }
      if (t === hl) a.setAttribute('aria-current', 'true'); else a.removeAttribute('aria-current');
    });
    // 語言切換觸發鈕的短碼隨當前語言變(繁中 / 简中 / EN);展開下拉仍是全名。
    var _code = { 'zh-hant': '繁中', 'zh-hans': '简中', 'en': 'EN' };
    document.querySelectorAll('.lang-cur').forEach(function (el) { el.textContent = _code[hl] || el.textContent; });
    // 跨網域到 my. 子網域會丟 localStorage(不同 origin);每個 my. CTA 補上目前語言 ?hl=,語言才不會亂跑。
    // (登入者的頭像選單由 mm-acct-menu 另補 hl;此處救未登入者的靜態「我的音樂劇」連結。)
    document.querySelectorAll('a.nav-cta[href^="https://my.themusicalmap.com"], a.cta[href^="https://my.themusicalmap.com"], #mine-link[href^="https://my.themusicalmap.com"]').forEach(function (a) {
      try { var mu = new URL(a.href); mu.searchParams.set('hl', hl); a.href = mu.href; } catch (e) {}
    });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', apply);
  else apply();
  window.MM_APPLY_I18N = apply;
})();
