"""Enrich venues with a Google place_id so map links open the venue's SINGLE place
card directly (?api=1&query=<name>&query_place_id=<pid>) — proven 2026-07-16 that this
resolves to the exact place card (e.g. Broadway Theatre 1681 Broadway) rather than a
results list, which plain name/coord queries cannot do for generic names.

Method: Places API (New) Text Search with locationBias = a circle around the venue's
known building coords, so the top result is the RIGHT venue even for ambiguous names
("Broadway Theatre"). The returned point must be within MAX_M of the stored coords or
the match is rejected (frontend then falls back to the coordinate-anchored search).

STORAGE: results go to data/venue_place_ids.json (persistent, keyed by "lat,lng" at 6dp),
NOT into venues_catalog.json — the catalog is a build artifact regenerated by
gen_catalog.py, which merges these pids in. This mirrors venue_coords.json.

COST SAFETY (money is the user's Google free-trial credit; must never exceed $300):
  * each venue is attempted AT MOST ONCE — result (pid or null) is persisted, never retried.
  * total calls <= number of venues (~5,426).
  * HARD CAP: MAX_CALLS aborts the run if exceeded — a deterministic runaway guard.
    Even worst case (all calls billed at the top Text Search Pro rate, zero free tier)
    5,600 * $0.032 ~= $179 < $300. Actual cost is read from the Cloud Billing console,
    never from a computed estimate.

KEY: env GOOGLE_MAPS_KEY else scrapers/.gmaps_key (gitignored).
Test:  python -u scrapers/enrich_place_ids.py --limit 20
Test:  python -u scrapers/enrich_place_ids.py --match "Broadway Theatre"
All:   python -u scrapers/enrich_place_ids.py
"""

import io
import json
import math
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
CATALOG = DATA / "venues_catalog.json"
STORE = DATA / "venue_place_ids.json"
SEARCH = "https://places.googleapis.com/v1/places:searchText"

MAX_M = 120          # returned place must be within this many metres of stored coords
BIAS_M = 300.0       # locationBias circle radius
MAX_CALLS = 5600     # HARD runaway cap — abort beyond this many API calls in one run
SLEEP = 0.08


def load_key():
    k = os.environ.get("GOOGLE_MAPS_KEY", "").strip()
    if k:
        return k
    f = ROOT / "scrapers" / ".gmaps_key"
    if f.exists():
        return f.read_text(encoding="utf-8").strip()
    sys.exit("No API key: set GOOGLE_MAPS_KEY or write scrapers/.gmaps_key")


def dist_m(a, b, c, d):
    R = 6371008.8
    p = math.pi / 180
    h = 0.5 - math.cos((c - a) * p) / 2 + math.cos(a * p) * math.cos(c * p) * (1 - math.cos((d - b) * p)) / 2
    return 2 * R * math.asin(math.sqrt(h))


def ckey(lat, lng):
    return f"{round(float(lat), 6)},{round(float(lng), 6)}"


def search(name, lat, lng, key):
    """Return {'id','lat','lng','name'} | ('DENIED', msg) | None."""
    payload = {
        "textQuery": name,
        "maxResultCount": 1,
        "locationBias": {"circle": {"center": {"latitude": lat, "longitude": lng}, "radius": BIAS_M}},
    }
    req = urllib.request.Request(SEARCH, data=json.dumps(payload).encode(), method="POST", headers={
        "Content-Type": "application/json", "X-Goog-Api-Key": key,
        "X-Goog-FieldMask": "places.id,places.location,places.displayName"})
    try:
        r = json.loads(urllib.request.urlopen(req, timeout=25).read())
    except urllib.error.HTTPError as e:
        msg = e.read().decode("utf-8", "ignore")[:200]
        return ("DENIED", msg) if e.code in (400, 403) else None
    except Exception:
        return None
    places = r.get("places") or []
    if not places:
        return None
    p = places[0]
    loc = p.get("location") or {}
    if "latitude" not in loc or not p.get("id"):
        return None
    return {"id": p["id"], "lat": loc["latitude"], "lng": loc["longitude"],
            "name": (p.get("displayName") or {}).get("text", "")}


def main():
    key = load_key()
    limit = int(sys.argv[sys.argv.index("--limit") + 1]) if "--limit" in sys.argv else None
    match = sys.argv[sys.argv.index("--match") + 1].lower() if "--match" in sys.argv else None

    cat = json.loads(CATALOG.read_text(encoding="utf-8"))
    venues = cat["venues"]
    store = json.loads(STORE.read_text(encoding="utf-8")) if STORE.exists() else {}

    todo = []
    for v in venues:
        if v.get("lat") is None or v.get("lng") is None:
            continue
        k = ckey(v["lat"], v["lng"])
        if k in store:                       # already attempted (pid or null) — never retry
            continue
        if match and match not in (v.get("name", "").lower()):
            continue
        todo.append((k, v))
    if limit:
        todo = todo[:limit]

    print(f"venues={len(venues)} already_done={len(store)} to_resolve={len(todo)} "
          f"(hard cap {MAX_CALLS} calls)", flush=True)
    if not todo:
        print("nothing to do.", flush=True)
        return

    calls = resolved = far = none = 0
    for i, (k, v) in enumerate(todo, 1):
        if calls >= MAX_CALLS:
            print(f"!! HARD CAP {MAX_CALLS} reached — aborting (safety).", flush=True)
            break
        res = search(v["name"], v["lat"], v["lng"], key)
        calls += 1
        time.sleep(SLEEP)
        if isinstance(res, tuple) and res[0] == "DENIED":
            print(f"!! DENIED (stopping): {res[1][:160]}", flush=True)
            break
        if not res:
            store[k] = None
            none += 1
        else:
            d = dist_m(v["lat"], v["lng"], res["lat"], res["lng"])
            if d <= MAX_M:
                store[k] = {"pid": res["id"], "name": res["name"], "m": round(d, 1)}
                resolved += 1
            else:
                store[k] = None            # too far → don't trust; frontend falls back
                far += 1
        if i % 25 == 0:
            STORE.write_text(json.dumps(store, ensure_ascii=False, indent=0), encoding="utf-8")
            print(f"  [{i}/{len(todo)}] calls={calls} resolved={resolved} far={far} none={none}", flush=True)

    STORE.write_text(json.dumps(store, ensure_ascii=False, indent=0), encoding="utf-8")
    print(f"\nDONE  calls={calls}  resolved={resolved}  far={far}  no-result={none}", flush=True)
    print(f"  store now has {len(store)} venue keys -> {STORE}", flush=True)
    print("  >> COST: read the ACTUAL amount from the Cloud Billing console; never trust a computed guess.", flush=True)


if __name__ == "__main__":
    main()
